/**
 * Support card type labels for deck recommendations.
 * Types mirror in-game support roles (Speed / Stamina / Power / Guts / Wit / Groupe).
 * Names must match keys in `src/data/supports.json`.
 */
export type SupportCardType = "Speed" | "Stamina" | "Power" | "Guts" | "Wit" | "Groupe"

export interface SupportCardMeta {
    name: string
    type: SupportCardType
}

/** Curated card types for supports shipped in `supports.json`. */
export const SUPPORT_CARD_CATALOG: Record<string, SupportCardMeta> = {
    "Admire Vega": { name: "Admire Vega", type: "Stamina" },
    "Agnes Digital": { name: "Agnes Digital", type: "Power" },
    "Agnes Tachyon": { name: "Agnes Tachyon", type: "Wit" },
    "Air Groove": { name: "Air Groove", type: "Power" },
    "Air Shakur": { name: "Air Shakur", type: "Wit" },
    "Aoi Kiryuin": { name: "Aoi Kiryuin", type: "Groupe" },
    "Bamboo Memory": { name: "Bamboo Memory", type: "Power" },
    "Biko Pegasus": { name: "Biko Pegasus", type: "Guts" },
    "Biwa Hayahide": { name: "Biwa Hayahide", type: "Stamina" },
    "Curren Chan": { name: "Curren Chan", type: "Speed" },
    "Daitaku Helios": { name: "Daitaku Helios", type: "Speed" },
    "Daiwa Scarlet": { name: "Daiwa Scarlet", type: "Power" },
    "Eishin Flash": { name: "Eishin Flash", type: "Stamina" },
    "El Condor Pasa": { name: "El Condor Pasa", type: "Speed" },
    "Fine Motion": { name: "Fine Motion", type: "Wit" },
    "Fuji Kiseki": { name: "Fuji Kiseki", type: "Wit" },
    "Gold City": { name: "Gold City", type: "Wit" },
    "Gold Ship": { name: "Gold Ship", type: "Guts" },
    "Grass Wonder": { name: "Grass Wonder", type: "Speed" },
    "Haru Urara": { name: "Haru Urara", type: "Guts" },
    "Hishi Akebono": { name: "Hishi Akebono", type: "Power" },
    "Hishi Amazon": { name: "Hishi Amazon", type: "Speed" },
    "Ikuno Dictus": { name: "Ikuno Dictus", type: "Stamina" },
    "Inari One": { name: "Inari One", type: "Power" },
    "Ines Fujin": { name: "Ines Fujin", type: "Speed" },
    "Kawakami Princess": { name: "Kawakami Princess", type: "Power" },
    "King Halo": { name: "King Halo", type: "Speed" },
    "Kitasan Black": { name: "Kitasan Black", type: "Speed" },
    "Manhattan Cafe": { name: "Manhattan Cafe", type: "Stamina" },
    "Maruzensky": { name: "Maruzensky", type: "Speed" },
    "Marvelous Sunday": { name: "Marvelous Sunday", type: "Speed" },
    "Matikanefukukitaru": { name: "Matikanefukukitaru", type: "Wit" },
    "Matikanetannhauser": { name: "Matikanetannhauser", type: "Guts" },
    "Mayano Top Gun": { name: "Mayano Top Gun", type: "Speed" },
    "Meisho Doto": { name: "Meisho Doto", type: "Stamina" },
    "Mejiro Ardan": { name: "Mejiro Ardan", type: "Stamina" },
    "Mejiro Bright": { name: "Mejiro Bright", type: "Stamina" },
    "Mejiro Dober": { name: "Mejiro Dober", type: "Stamina" },
    "Mejiro McQueen": { name: "Mejiro McQueen", type: "Stamina" },
    "Mejiro Palmer": { name: "Mejiro Palmer", type: "Wit" },
    "Mejiro Ryan": { name: "Mejiro Ryan", type: "Stamina" },
    "Mihono Bourbon": { name: "Mihono Bourbon", type: "Stamina" },
    "Mr. C.B.": { name: "Mr. C.B.", type: "Guts" },
    "Nakayama Festa": { name: "Nakayama Festa", type: "Guts" },
    "Narita Brian": { name: "Narita Brian", type: "Power" },
    "Narita Taishin": { name: "Narita Taishin", type: "Speed" },
    "Narita Top Road": { name: "Narita Top Road", type: "Stamina" },
    "Nice Nature": { name: "Nice Nature", type: "Speed" },
    "Nishino Flower": { name: "Nishino Flower", type: "Wit" },
    "Oguri Cap": { name: "Oguri Cap", type: "Power" },
    "Rice Shower": { name: "Rice Shower", type: "Stamina" },
    "Riko Kashimoto": { name: "Riko Kashimoto", type: "Groupe" },
    "Sakura Bakushin O": { name: "Sakura Bakushin O", type: "Speed" },
    "Sakura Chiyono O": { name: "Sakura Chiyono O", type: "Speed" },
    "Sasami Anshinzawa": { name: "Sasami Anshinzawa", type: "Groupe" },
    "Satono Diamond": { name: "Satono Diamond", type: "Power" },
    "Seeking the Pearl": { name: "Seeking the Pearl", type: "Speed" },
    "Seiun Sky": { name: "Seiun Sky", type: "Wit" },
    "Shinko Windy": { name: "Shinko Windy", type: "Speed" },
    "Silence Suzuka": { name: "Silence Suzuka", type: "Speed" },
    "Sirius Symboli": { name: "Sirius Symboli", type: "Stamina" },
    "Smart Falcon": { name: "Smart Falcon", type: "Speed" },
    "Special Week": { name: "Special Week", type: "Speed" },
    "Super Creek": { name: "Super Creek", type: "Stamina" },
    "Sweep Tosho": { name: "Sweep Tosho", type: "Wit" },
    "Symboli Rudolf": { name: "Symboli Rudolf", type: "Guts" },
    "TM Opera O": { name: "TM Opera O", type: "Speed" },
    "Taiki Shuttle": { name: "Taiki Shuttle", type: "Speed" },
    "Tamamo Cross": { name: "Tamamo Cross", type: "Guts" },
    "Tazuna Hayakawa": { name: "Tazuna Hayakawa", type: "Groupe" },
    "Team Sirius": { name: "Team Sirius", type: "Groupe" },
    "Tokai Teio": { name: "Tokai Teio", type: "Speed" },
    "Tosen Jordan": { name: "Tosen Jordan", type: "Stamina" },
    "Twin Turbo": { name: "Twin Turbo", type: "Speed" },
    "Vodka": { name: "Vodka", type: "Speed" },
    "Winning Ticket": { name: "Winning Ticket", type: "Guts" },
    "Yaeno Muteki": { name: "Yaeno Muteki", type: "Speed" },
    "Yukino Bijin": { name: "Yukino Bijin", type: "Speed" },
    "Zenno Rob Roy": { name: "Zenno Rob Roy", type: "Stamina" },
}

export const supportCardType = (name: string): SupportCardType | undefined => SUPPORT_CARD_CATALOG[name]?.type
